# zkp-dh: Zero-knowledge proof generator and verifier for one party to show
# to another that their Diffie-Hellman shared secret is correct.
# See the Camenisch and Stadler paper for procedural specifics on ZKP
# proof generation, such as knowledge of discrete logarithm.

# Lining Wang, June 2014

import random
import hashlib
import binascii
from Crypto.Util.number import bytes_to_long

# converts from a string to a long
def _strtoLong(s):
    s = bytes("".join(s.split()), "UTF-8")
    s = binascii.a2b_hex(s)
    return bytes_to_long(s)

# DiffieHellman class enables construction of keys capable of performing
# D-H exchanges, and interactive proof of knowledge
class DiffieHellman:
    # Temporary base and prime
    P = _strtoLong("B10B8F96 A080E01D DE92DE5E AE5D54EC 52C99FBC FB06A3C6"
    "9A6A9DCA 52D23B61 6073E286 75A23D18 9838EF1E 2EE652C0"
    "13ECB4AE A9061123 24975C3C D49B83BF ACCBDD7D 90C4BD70"
    "98488E9C 219A7372 4EFFD6FA E5644738 FAA31A4F F55BCCC0"
    "A151AF5F 0DC8B4BD 45BF37DF 365C1A65 E68CFDA7 6D4DA708"
    "DF1FB2BC 2E4A4371")

    G = _strtoLong("A4D1CBD5 C3FD3412 6765A442 EFB99905 F8104DD2 58AC507F"
    "D6406CFF 14266D31 266FEA1E 5C41564B 777E690F 5504F213"
    "160217B4 B01B886A 5E91547F 9E2749F4 D7FBD7D3 B9A92EE1"
    "909D0D22 63F80A76 A6A24C08 7A091F53 1DBF0A01 69B6A28A"
    "D662A4D1 8E73AFA3 2D779D59 18D08BC8 858F4DCE F97C2A24"
    "855E6EEB 22B3B2E5")

    def __init__(self):
        self.secret = random.randrange(1 << (self.G.bit_length() - 1), self.G - 1)
        self.public = pow(self.G, self.secret, self.P)

    # get shared secret: (g^b)^a mod p
    def get_shared_secret(self, remote_pub):
        return pow(remote_pub, self.secret, self.P)

    # Given the public key of B (remote_pub), shows that the shared secret
    # between A and B was generated by A.
    # Returns zero-knowledge proof of shared Diffie-Hellman secret between A & B.
    def prove_shared_secret(self, remote_pub):
        G = self.G; prover_pub = self.public; phi = self. P - 1;
        secret = self.get_shared_secret(remote_pub)

        # Random key in the group Z_q
        randKey = DiffieHellman() # random secret
        commit1 = randKey.public
        commit2 = randKey.get_shared_secret(remote_pub)

        # shift and hash
        concat = str(G) + str(prover_pub) + str(remote_pub) + str(secret) + str(commit1) + str(commit2)
        h = hashlib.md5()
        h.update(concat.encode("utf-8"))
        challenge = int(h.hexdigest(), 16)
        product = (self.secret * challenge) % phi
        response = (randKey.secret - product) % phi

        return (secret, challenge, response)

    # Verifies proof generated above. Verifier c is showing that
    # shared secret between A and B was generated by A.
    # returns 0 if if verification fails; returns shared secret otherwise
    def verify_shared_secret(self, prover_pub, remote_pub, secret, challenge,
     response):
        P = self.P; G = self.G ; public = self.public

        # g^r * (a's public key)^challenge
        commit1 = (pow(G, response, P) * pow(public, challenge, P)) % P

        # (b's public key)^response * (secret)^challenge
        commit2 = (pow(remote_pub, response, P) * pow(secret, challenge, P)) % P

        # Shift and hash
        hasher = hashlib.md5()
        concat = str(G) + str(prover_pub) + str(remote_pub) + str(secret) + str(commit1) + str(commit2)
        hasher.update(concat.encode("utf-8"))
        check = int(hasher.hexdigest(), 16)

        if challenge == check:
            return secret
        else:
            return 0

def main():
    a = DiffieHellman()
    b = DiffieHellman()
    results = a.prove_shared_secret(b.public)
    assert a.verify_shared_secret(a.public, b.public, results[0],  \
        results[1], results[2])

if __name__ == "__main__":
    main()
